import { useState, useRef, useCallback } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { motion, AnimatePresence } from "framer-motion";
import { apiFetch } from "@/lib/api";
import { formatCurrency, formatNumber } from "@/lib/utils";
import { BarcodeDisplay, BarcodePrintLabel } from "@/components/barcode-display";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from "@/components/ui/dialog";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Skeleton } from "@/components/ui/skeleton";
import {
  Plus, Search, Pencil, Trash2, Package, AlertTriangle, ScanBarcode,
  Eye, Printer, Download, Tag, X
} from "lucide-react";
import { useToast } from "@/hooks/use-toast";

interface Item {
  id: number;
  code: string;
  name: string;
  barcode: string | null;
  categoryId: number | null;
  unitId: number | null;
  supplierId: number | null;
  description: string | null;
  minimumStock: number;
  currentStock: number;
  unitPrice: string | null;
  categoryName?: string;
  unitName?: string;
  supplierName?: string;
  status?: string;
}

interface Category { id: number; name: string; }
interface Unit { id: number; name: string; }
interface Supplier { id: number; name: string; }

/* ── Animation Variants ─────────────────────────────────────── */
const fadeIn = { initial: { opacity: 0, y: 12 }, animate: { opacity: 1, y: 0 }, exit: { opacity: 0, y: -12 } };
const scaleIn = { initial: { opacity: 0, scale: 0.92 }, animate: { opacity: 1, scale: 1 }, exit: { opacity: 0, scale: 0.92 } };
const slideUp = { initial: { opacity: 0, y: 40 }, animate: { opacity: 1, y: 0 }, exit: { opacity: 0, y: 40 } };
const stagger = { animate: { transition: { staggerChildren: 0.04 } } };

export default function BarangPage() {
  const [search, setSearch] = useState("");
  const [dialogOpen, setDialogOpen] = useState(false);
  const [deleteId, setDeleteId] = useState<number | null>(null);
  const [editing, setEditing] = useState<Item | null>(null);
  const [detailItem, setDetailItem] = useState<Item | null>(null);
  const [scanOpen, setScanOpen] = useState(false);
  const [scanInput, setScanInput] = useState("");
  const [scanResult, setScanResult] = useState<Item | null>(null);
  const [scanLoading, setScanLoading] = useState(false);
  const [scanError, setScanError] = useState("");
  const scanRef = useRef<HTMLInputElement>(null);

  const [form, setForm] = useState({
    code: "", name: "", barcode: "", categoryId: "", unitId: "", supplierId: "",
    description: "", minimumStock: "0", unitPrice: "",
  });
  const { toast } = useToast();
  const qc = useQueryClient();

  const { data: items, isLoading } = useQuery({
    queryKey: ["items", search],
    queryFn: () => apiFetch<Item[]>(`/api/items?search=${encodeURIComponent(search)}`),
  });
  const { data: categories } = useQuery({ queryKey: ["categories"], queryFn: () => apiFetch<Category[]>("/api/categories") });
  const { data: units } = useQuery({ queryKey: ["units"], queryFn: () => apiFetch<Unit[]>("/api/units") });
  const { data: suppliers } = useQuery({ queryKey: ["suppliers"], queryFn: () => apiFetch<Supplier[]>("/api/suppliers") });

  /* ── Mutations ─────────────────────────────────────────────── */
  const saveMutation = useMutation({
    mutationFn: async () => {
      const body = {
        code: form.code, name: form.name,
        barcode: null, // Auto-generated by backend
        categoryId: form.categoryId ? parseInt(form.categoryId) : null,
        unitId: form.unitId ? parseInt(form.unitId) : null,
        supplierId: form.supplierId ? parseInt(form.supplierId) : null,
        description: form.description || null,
        minimumStock: parseInt(form.minimumStock) || 0,
        currentStock: 0,
        unitPrice: form.unitPrice ? parseFloat(form.unitPrice) : 0,
      };
      if (editing) {
        return apiFetch(`/api/items/${editing.id}`, { method: "PATCH", body: JSON.stringify(body) });
      }
      return apiFetch("/api/items", { method: "POST", body: JSON.stringify(body) });
    },
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ["items"] });
      setDialogOpen(false);
      toast({ title: editing ? "Barang diperbarui" : "Barang ditambahkan" });
    },
    onError: (e: Error) => toast({ title: "Error", description: e.message, variant: "destructive" }),
  });

  const deleteMutation = useMutation({
    mutationFn: (id: number) => apiFetch(`/api/items/${id}`, { method: "DELETE" }),
    onSuccess: () => { qc.invalidateQueries({ queryKey: ["items"] }); setDeleteId(null); toast({ title: "Barang dihapus" }); },
    onError: (e: Error) => toast({ title: "Error", description: e.message, variant: "destructive" }),
  });

  /* ── Handlers ──────────────────────────────────────────────── */
  const openCreate = () => {
    setEditing(null);
    setForm({ code: "", name: "", barcode: "", categoryId: "", unitId: "", supplierId: "", description: "", minimumStock: "0", unitPrice: "" });
    setDialogOpen(true);
  };

  const openEdit = (item: Item) => {
    setEditing(item);
    setForm({
      code: item.code, name: item.name, barcode: item.barcode ?? "",
      categoryId: item.categoryId?.toString() ?? "", unitId: item.unitId?.toString() ?? "",
      supplierId: item.supplierId?.toString() ?? "", description: item.description ?? "",
      minimumStock: item.minimumStock.toString(), unitPrice: item.unitPrice ?? "",
    });
    setDialogOpen(true);
  };

  const handleScan = useCallback(async () => {
    const q = scanInput.trim();
    if (!q) return;
    setScanLoading(true);
    setScanError("");
    setScanResult(null);
    try {
      const result = await apiFetch<Item>(`/api/items/barcode/${encodeURIComponent(q)}`);
      setScanResult(result);
    } catch {
      setScanError("Barang dengan barcode tersebut tidak ditemukan.");
    } finally {
      setScanLoading(false);
    }
  }, [scanInput]);

  const handleScanKey = (e: React.KeyboardEvent) => {
    if (e.key === "Enter") handleScan();
  };

  /* ── Print / Download ──────────────────────────────────────── */
  const handlePrint = (item: Item) => {
    const printWindow = window.open("", "_blank", "width=400,height=500");
    if (!printWindow) return;
    const svg = document.getElementById("barcode-detail-svg");
    const svgHtml = svg?.outerHTML ?? "";
    printWindow.document.write(`
      <html><head><title>Barcode - ${item.name}</title>
      <style>body{display:flex;flex-direction:column;align-items:center;justify-content:center;min-height:100vh;font-family:sans-serif;margin:0;}
      h3{margin:0 0 4px;}p{margin:0;color:#666;font-family:monospace;}</style></head>
      <body><h3>${item.name}</h3><p>${item.code}</p><div style="margin:12px 0">${svgHtml}</div><p>${item.barcode ?? ""}</p>
      <script>setTimeout(()=>window.print(),300);</script></body></html>
    `);
    printWindow.document.close();
  };

  const handleDownload = (item: Item) => {
    const svg = document.getElementById("barcode-detail-svg");
    if (!svg) return;
    const svgData = new XMLSerializer().serializeToString(svg);
    const canvas = document.createElement("canvas");
    const ctx = canvas.getContext("2d");
    const img = new Image();
    img.onload = () => {
      canvas.width = img.width;
      canvas.height = img.height;
      ctx?.drawImage(img, 0, 0);
      const link = document.createElement("a");
      link.download = `qr-${item.code}.png`;
      link.href = canvas.toDataURL("image/png");
      link.click();
    };
    img.src = "data:image/svg+xml;base64," + btoa(unescape(encodeURIComponent(svgData)));
  };

  const handlePrintLabel = (item: Item) => {
    const printWindow = window.open("", "_blank", "width=400,height=600");
    if (!printWindow) return;
    const svg = document.getElementById("barcode-detail-svg");
    const svgHtml = svg?.outerHTML ?? "";
    printWindow.document.write(`
      <html><head><title>Label - ${item.name}</title>
      <style>body{display:flex;flex-direction:column;align-items:center;justify-content:center;min-height:100vh;font-family:sans-serif;margin:0;padding:24px;}
      .label{border:2px dashed #ccc;border-radius:12px;padding:24px;text-align:center;min-width:240px;}
      h2{margin:0 0 4px;font-size:16px;}p{margin:2px 0;color:#333;font-size:13px;font-family:monospace;}</style></head>
      <body><div class="label"><h2>${item.name}</h2><p>Kode: ${item.code}</p><div style="margin:16px 0">${svgHtml}</div>
      <p>${item.barcode ?? ""}</p></div>
      <script>setTimeout(()=>window.print(),300);</script></body></html>
    `);
    printWindow.document.close();
  };

  /* ── Render ────────────────────────────────────────────────── */
  return (
    <div className="p-6 space-y-4">
      {/* Header */}
      <motion.div
        className="flex flex-col sm:flex-row sm:items-center justify-between gap-3"
        initial={{ opacity: 0, y: -20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.4 }}
      >
        <div>
          <h1 className="text-2xl font-bold">Master Barang</h1>
          <p className="text-muted-foreground text-sm">Kelola data barang inventaris</p>
        </div>
        <div className="flex gap-2">
          <Button variant="outline" onClick={() => { setScanOpen(true); setScanInput(""); setScanResult(null); setScanError(""); }}>
            <ScanBarcode className="w-4 h-4 mr-2" /> Scan Barcode
          </Button>
          <Button onClick={openCreate}><Plus className="w-4 h-4 mr-2" /> Tambah Barang</Button>
        </div>
      </motion.div>

      {/* Table */}
      <motion.div initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.5, delay: 0.1 }}>
        <Card>
          <CardHeader className="pb-3">
            <div className="relative">
              <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" />
              <Input placeholder="Cari nama, kode, barcode..." className="pl-9" value={search} onChange={(e) => setSearch(e.target.value)} />
            </div>
          </CardHeader>
          <CardContent className="p-0">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Kode</TableHead>
                  <TableHead>Nama Barang</TableHead>
                  <TableHead>Kategori</TableHead>
                  <TableHead>Satuan</TableHead>
                  <TableHead className="text-right">Stok</TableHead>
                  <TableHead className="text-center">Barcode</TableHead>
                  <TableHead>Status</TableHead>
                  <TableHead className="text-right">Aksi</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {isLoading ? (
                  Array(5).fill(0).map((_, i) => (
                    <TableRow key={i}><TableCell colSpan={8}><Skeleton className="h-8 w-full" /></TableCell></TableRow>
                  ))
                ) : !items?.length ? (
                  <TableRow>
                    <TableCell colSpan={8} className="text-center py-12 text-muted-foreground">
                      <Package className="w-8 h-8 mx-auto mb-2 opacity-30" />
                      <p>Belum ada data barang</p>
                    </TableCell>
                  </TableRow>
                ) : (
                  <AnimatePresence>
                    <motion.tbody variants={stagger} initial="initial" animate="animate">
                      {items.map((item, idx) => (
                        <motion.tr
                          key={item.id}
                          variants={fadeIn}
                          transition={{ duration: 0.3, delay: idx * 0.03 }}
                          className="border-b transition-colors hover:bg-muted/50 data-[state=selected]:bg-muted"
                          layout
                        >
                          <TableCell className="font-mono text-sm">{item.code}</TableCell>
                          <TableCell>
                            <p className="font-medium">{item.name}</p>
                          </TableCell>
                          <TableCell>{item.categoryName ?? "-"}</TableCell>
                          <TableCell>{item.unitName ?? "-"}</TableCell>
                          <TableCell className="text-right">
                            <Badge variant={item.currentStock <= item.minimumStock ? "destructive" : "secondary"}>
                              {item.currentStock <= item.minimumStock && <AlertTriangle className="w-3 h-3 mr-1" />}
                              {formatNumber(item.currentStock)}
                            </Badge>
                          </TableCell>
                          <TableCell className="text-center">
                            {item.barcode ? (
                              <motion.div
                                whileHover={{ scale: 1.15 }}
                                transition={{ type: "spring", stiffness: 400, damping: 15 }}
                                className="inline-block cursor-pointer"
                                onClick={() => setDetailItem(item)}
                              >
                                <BarcodeDisplay value={item.barcode} size={36} />
                              </motion.div>
                            ) : (
                              <span className="text-xs text-muted-foreground">-</span>
                            )}
                          </TableCell>
                          <TableCell>
                            <Badge variant={(item.status ?? "active") === "active" ? "default" : "secondary"}>
                              {(item.status ?? "active") === "active" ? "Aktif" : "Nonaktif"}
                            </Badge>
                          </TableCell>
                          <TableCell className="text-right">
                            <div className="flex justify-end gap-1">
                              <motion.div whileHover={{ scale: 1.1 }} whileTap={{ scale: 0.9 }}>
                                <Button size="icon" variant="ghost" className="h-8 w-8" onClick={() => setDetailItem(item)}>
                                  <Eye className="w-4 h-4" />
                                </Button>
                              </motion.div>
                              <motion.div whileHover={{ scale: 1.1 }} whileTap={{ scale: 0.9 }}>
                                <Button size="icon" variant="ghost" className="h-8 w-8" onClick={() => openEdit(item)}>
                                  <Pencil className="w-4 h-4" />
                                </Button>
                              </motion.div>
                              <motion.div whileHover={{ scale: 1.1 }} whileTap={{ scale: 0.9 }}>
                                <Button size="icon" variant="ghost" className="h-8 w-8 text-red-600 hover:text-red-700 hover:bg-red-50" onClick={() => setDeleteId(item.id)}>
                                  <Trash2 className="w-4 h-4" />
                                </Button>
                              </motion.div>
                            </div>
                          </TableCell>
                        </motion.tr>
                      ))}
                    </motion.tbody>
                  </AnimatePresence>
                )}
              </TableBody>
            </Table>
          </CardContent>
        </Card>
      </motion.div>

      {/* ── Dialog: Add/Edit Barang ────────────────────────────── */}
      <Dialog open={dialogOpen} onOpenChange={setDialogOpen}>
        <DialogContent className="max-w-lg max-h-[90vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle>{editing ? "Edit Barang" : "Tambah Barang"}</DialogTitle>
          </DialogHeader>
          <motion.div className="grid grid-cols-2 gap-4 py-2" {...scaleIn} transition={{ duration: 0.3 }}>
            <div className="space-y-1.5">
              <Label>Kode Barang *</Label>
              <Input value={form.code} onChange={(e) => setForm(f => ({ ...f, code: e.target.value }))} placeholder="ATK-001" />
            </div>
            <div className="space-y-1.5">
              <Label>Barcode</Label>
              <Input
                value={editing?.barcode ?? "AUTO GENERATED"}
                readOnly
                disabled
                className="bg-muted font-mono text-xs cursor-not-allowed"
              />
            </div>
            <div className="space-y-1.5 col-span-2">
              <Label>Nama Barang *</Label>
              <Input value={form.name} onChange={(e) => setForm(f => ({ ...f, name: e.target.value }))} placeholder="Nama lengkap barang" />
            </div>
            <div className="space-y-1.5">
              <Label>Kategori</Label>
              <Select value={form.categoryId} onValueChange={(v) => setForm(f => ({ ...f, categoryId: v }))}>
                <SelectTrigger><SelectValue placeholder="Pilih kategori" /></SelectTrigger>
                <SelectContent className="z-[100]">
                  {categories && categories.length > 0
                    ? categories.map(c => <SelectItem key={c.id} value={c.id.toString()}>{c.name}</SelectItem>)
                    : <SelectItem disabled value="empty">Belum ada kategori</SelectItem>}
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-1.5">
              <Label>Satuan</Label>
              <Select value={form.unitId} onValueChange={(v) => setForm(f => ({ ...f, unitId: v }))}>
                <SelectTrigger><SelectValue placeholder="Pilih satuan" /></SelectTrigger>
                <SelectContent className="z-[100]">
                  {units && units.length > 0
                    ? units.map(u => <SelectItem key={u.id} value={u.id.toString()}>{u.name}</SelectItem>)
                    : <SelectItem disabled value="empty">Belum ada satuan</SelectItem>}
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-1.5">
              <Label>Supplier</Label>
              <Select value={form.supplierId} onValueChange={(v) => setForm(f => ({ ...f, supplierId: v }))}>
                <SelectTrigger><SelectValue placeholder="Pilih supplier" /></SelectTrigger>
                <SelectContent className="z-[100]">
                  {suppliers && suppliers.length > 0
                    ? suppliers.map(s => <SelectItem key={s.id} value={s.id.toString()}>{s.name}</SelectItem>)
                    : <SelectItem disabled value="empty">Belum ada supplier</SelectItem>}
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-1.5">
              <Label>Stok Minimum</Label>
              <Input type="number" min="0" value={form.minimumStock} onChange={(e) => setForm(f => ({ ...f, minimumStock: e.target.value }))} />
            </div>
            <div className="space-y-1.5 col-span-2">
              <Label>Harga Satuan (Rp)</Label>
              <Input type="number" min="0" value={form.unitPrice} onChange={(e) => setForm(f => ({ ...f, unitPrice: e.target.value }))} placeholder="0" />
            </div>
            <div className="space-y-1.5 col-span-2">
              <Label>Deskripsi</Label>
              <Textarea value={form.description} onChange={(e) => setForm(f => ({ ...f, description: e.target.value }))} rows={3} placeholder="Keterangan tambahan..." />
            </div>
          </motion.div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setDialogOpen(false)}>Batal</Button>
            <Button onClick={() => saveMutation.mutate()} disabled={!form.code || !form.name || saveMutation.isPending}>
              {saveMutation.isPending ? "Menyimpan..." : "Simpan"}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* ── Dialog: Delete Barang ─────────────────────────────── */}
      <Dialog open={deleteId !== null} onOpenChange={(o) => !o && setDeleteId(null)}>
        <DialogContent>
          <DialogHeader><DialogTitle>Hapus Barang</DialogTitle></DialogHeader>
          <p className="text-sm text-muted-foreground">Apakah Anda yakin ingin menghapus barang ini? Tindakan ini tidak dapat dibatalkan.</p>
          <DialogFooter>
            <Button variant="outline" onClick={() => setDeleteId(null)}>Batal</Button>
            <Button variant="destructive" onClick={() => deleteId && deleteMutation.mutate(deleteId)} disabled={deleteMutation.isPending}>
              {deleteMutation.isPending ? "Menghapus..." : "Hapus"}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* ── Dialog: Detail Barang ─────────────────────────────── */}
      <Dialog open={detailItem !== null} onOpenChange={(o) => !o && setDetailItem(null)}>
        <DialogContent className="max-w-md">
          <DialogHeader><DialogTitle>Detail Barang</DialogTitle></DialogHeader>
          {detailItem && (
            <motion.div className="space-y-4" {...scaleIn} transition={{ duration: 0.35, type: "spring", stiffness: 300 }}>
              <div className="text-center space-y-1">
                <h3 className="font-semibold text-lg">{detailItem.name}</h3>
                <p className="text-sm text-muted-foreground font-mono">{detailItem.code}</p>
              </div>

              {/* QR Code Display */}
              {detailItem.barcode && (
                <motion.div
                  className="flex flex-col items-center gap-2 py-4 border rounded-xl bg-muted/30"
                  initial={{ opacity: 0, scale: 0.8 }}
                  animate={{ opacity: 1, scale: 1 }}
                  transition={{ delay: 0.15, type: "spring", stiffness: 300, damping: 20 }}
                >
                  <p className="text-xs font-medium text-muted-foreground uppercase tracking-wider">QR Code Barang</p>
                  <div id="barcode-detail-svg">
                    <BarcodeDisplay value={detailItem.barcode} size={160} showValue />
                  </div>
                  <p className="font-mono text-sm">{detailItem.barcode}</p>
                </motion.div>
              )}

              {/* Info Grid */}
              <motion.div
                className="grid grid-cols-2 gap-x-4 gap-y-2 text-sm"
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                transition={{ delay: 0.25 }}
              >
                <div><span className="text-muted-foreground">Kategori</span><p className="font-medium">{detailItem.categoryName ?? "-"}</p></div>
                <div><span className="text-muted-foreground">Satuan</span><p className="font-medium">{detailItem.unitName ?? "-"}</p></div>
                <div><span className="text-muted-foreground">Stok Saat Ini</span><p className="font-medium">{formatNumber(detailItem.currentStock)}</p></div>
                <div><span className="text-muted-foreground">Stok Minimum</span><p className="font-medium">{formatNumber(detailItem.minimumStock)}</p></div>
                <div><span className="text-muted-foreground">Harga Satuan</span><p className="font-medium">{formatCurrency(detailItem.unitPrice)}</p></div>
                <div><span className="text-muted-foreground">Supplier</span><p className="font-medium">{detailItem.supplierName ?? "-"}</p></div>
                <div><span className="text-muted-foreground">Status</span>
                  <Badge variant={(detailItem.status ?? "active") === "active" ? "default" : "secondary"}>
                    {(detailItem.status ?? "active") === "active" ? "Aktif" : "Nonaktif"}
                  </Badge>
                </div>
                {detailItem.description && (
                  <div className="col-span-2"><span className="text-muted-foreground">Deskripsi</span><p>{detailItem.description}</p></div>
                )}
              </motion.div>

              {/* Action Buttons */}
              {detailItem.barcode && (
                <motion.div
                  className="flex flex-wrap gap-2 pt-2"
                  initial={{ opacity: 0, y: 10 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ delay: 0.35 }}
                >
                  <Button size="sm" variant="outline" onClick={() => handlePrint(detailItem)}>
                    <Printer className="w-3.5 h-3.5 mr-1.5" /> Print QR
                  </Button>
                  <Button size="sm" variant="outline" onClick={() => handleDownload(detailItem)}>
                    <Download className="w-3.5 h-3.5 mr-1.5" /> Download QR
                  </Button>
                  <Button size="sm" variant="outline" onClick={() => handlePrintLabel(detailItem)}>
                    <Tag className="w-3.5 h-3.5 mr-1.5" /> Print Label
                  </Button>
                </motion.div>
              )}
            </motion.div>
          )}
          <DialogFooter>
            <Button onClick={() => setDetailItem(null)}>Tutup</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* ── Dialog: Scan Barcode ──────────────────────────────── */}
      <Dialog open={scanOpen} onOpenChange={(o) => { if (!o) { setScanOpen(false); setScanResult(null); setScanError(""); } }}>
        <DialogContent className="max-w-md">
          <DialogHeader><DialogTitle className="flex items-center gap-2"><ScanBarcode className="w-5 h-5" /> Scan Barcode</DialogTitle></DialogHeader>
          <motion.div className="space-y-4" {...fadeIn} transition={{ duration: 0.3 }}>
            <div className="space-y-1.5">
              <Label>Masukkan / Scan Barcode</Label>
              <div className="flex gap-2">
                <Input
                  ref={scanRef}
                  value={scanInput}
                  onChange={(e) => setScanInput(e.target.value)}
                  onKeyDown={handleScanKey}
                  placeholder="Scan barcode atau ketik kode..."
                  className="font-mono"
                  autoFocus
                />
                <Button onClick={handleScan} disabled={!scanInput.trim() || scanLoading}>
                  {scanLoading ? "Mencari..." : "Cari"}
                </Button>
              </div>
            </div>

            <AnimatePresence mode="wait">
              {scanError && (
                <motion.div
                  key="error"
                  {...slideUp}
                  transition={{ duration: 0.3 }}
                  className="p-3 rounded-lg bg-destructive/10 text-destructive text-sm flex items-center gap-2"
                >
                  <AlertTriangle className="w-4 h-4 shrink-0" />
                  {scanError}
                </motion.div>
              )}
              {scanResult && (
                <motion.div
                  key="result"
                  {...slideUp}
                  transition={{ duration: 0.4, type: "spring", stiffness: 300, damping: 25 }}
                  className="border rounded-xl p-4 space-y-3 bg-muted/30"
                >
                  <div className="flex items-start gap-3">
                    {scanResult.barcode && (
                      <motion.div
                        initial={{ opacity: 0, rotate: -10 }}
                        animate={{ opacity: 1, rotate: 0 }}
                        transition={{ delay: 0.2, type: "spring" }}
                      >
                        <BarcodeDisplay value={scanResult.barcode} size={64} />
                      </motion.div>
                    )}
                    <div className="flex-1 min-w-0">
                      <h4 className="font-semibold">{scanResult.name}</h4>
                      <p className="font-mono text-sm text-muted-foreground">{scanResult.code}</p>
                    </div>
                  </div>
                  <div className="grid grid-cols-2 gap-2 text-sm">
                    <div><span className="text-muted-foreground">Kategori:</span> <span className="font-medium">{scanResult.categoryName ?? "-"}</span></div>
                    <div><span className="text-muted-foreground">Satuan:</span> <span className="font-medium">{scanResult.unitName ?? "-"}</span></div>
                    <div><span className="text-muted-foreground">Stok:</span> <span className="font-medium">{formatNumber(scanResult.currentStock)}</span></div>
                    <div><span className="text-muted-foreground">Status:</span>{" "}
                      <Badge variant={(scanResult.status ?? "active") === "active" ? "default" : "secondary"} className="text-xs">
                        {(scanResult.status ?? "active") === "active" ? "Aktif" : "Nonaktif"}
                      </Badge>
                    </div>
                  </div>
                  <Button size="sm" variant="outline" className="w-full" onClick={() => { setDetailItem(scanResult); setScanOpen(false); }}>
                    <Eye className="w-3.5 h-3.5 mr-1.5" /> Lihat Detail Lengkap
                  </Button>
                </motion.div>
              )}
            </AnimatePresence>
          </motion.div>
          <DialogFooter>
            <Button variant="outline" onClick={() => { setScanOpen(false); setScanResult(null); setScanError(""); }}>Tutup</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}
