import { useState, useRef, useCallback } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { motion, AnimatePresence } from "framer-motion";
import { apiFetch } from "@/lib/api";
import { formatNumber } from "@/lib/utils";
import { BarcodeDisplay, BarcodePrintLabel } from "@/components/barcode-display";
import { BarcodeScanner } from "@/components/barcode-scanner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from "@/components/ui/dialog";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Skeleton } from "@/components/ui/skeleton";
import {
  Plus, Search, Pencil, Trash2, Package, AlertTriangle, Camera,
  Eye, Printer, Download, Tag, X
} from "lucide-react";
import { useToast } from "@/hooks/use-toast";

interface Item {
  id: number;
  code: string;
  name: string;
  barcode: string | null;
  categoryId: number | null;
  unitId: number | null;
  supplierId: number | null;
  description: string | null;
  minimumStock: number;
  currentStock: number;
  unitPrice: string | null;
  categoryName?: string;
  unitName?: string;
  supplierName?: string;
  status?: string;
  trackingType?: string;
}

interface Category { id: number; name: string; }
interface Unit { id: number; name: string; }
interface Supplier { id: number; name: string; }

export default function BarangPage() {
  const [search, setSearch] = useState("");
  const [dialogOpen, setDialogOpen] = useState(false);
  const [deleteId, setDeleteId] = useState<number | null>(null);
  const [editing, setEditing] = useState<Item | null>(null);
  const [detailItem, setDetailItem] = useState<Item | null>(null);
  /* Camera scanner states */
  const [cameraScanOpen, setCameraScanOpen] = useState(false);
  const [scanResult, setScanResult] = useState<Item | null>(null);
  const [scanError, setScanError] = useState("");
  /* Manual scan input */
  const [manualScanOpen, setManualScanOpen] = useState(false);
  const [manualInput, setManualInput] = useState("");
  const [manualLoading, setManualLoading] = useState(false);

  const [form, setForm] = useState({
    code: "", name: "", barcode: "", categoryId: "", unitId: "", supplierId: "",
    description: "", minimumStock: "0", unitPrice: "",
  });
  const { toast } = useToast();
  const qc = useQueryClient();

  const { data: items, isLoading } = useQuery({
    queryKey: ["items", search],
    queryFn: () => apiFetch<Item[]>(`/api/items?search=${encodeURIComponent(search)}`),
  });
  const { data: categories } = useQuery({ queryKey: ["categories"], queryFn: () => apiFetch<Category[]>("/api/categories") });
  const { data: units } = useQuery({ queryKey: ["units"], queryFn: () => apiFetch<Unit[]>("/api/units") });
  const { data: suppliers } = useQuery({ queryKey: ["suppliers"], queryFn: () => apiFetch<Supplier[]>("/api/suppliers") });

  /* ── Mutations ─────────────────────────────────────────────── */
  const saveMutation = useMutation({
    mutationFn: async () => {
      const body = {
        code: form.code, name: form.name,
        barcode: null, // Auto-generated by backend
        categoryId: form.categoryId ? parseInt(form.categoryId) : null,
        unitId: form.unitId ? parseInt(form.unitId) : null,
        supplierId: form.supplierId ? parseInt(form.supplierId) : null,
        description: form.description || null,
        minimumStock: parseInt(form.minimumStock) || 0,
        currentStock: 0,
        unitPrice: form.unitPrice ? parseFloat(form.unitPrice) : 0,
      };
      if (editing) {
        return apiFetch(`/api/items/${editing.id}`, { method: "PATCH", body: JSON.stringify(body) });
      }
      return apiFetch("/api/items", { method: "POST", body: JSON.stringify(body) });
    },
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ["items"] });
      setDialogOpen(false);
      toast({ title: editing ? "Barang diperbarui" : "Barang ditambahkan" });
    },
    onError: (e: Error) => toast({ title: "Error", description: e.message, variant: "destructive" }),
  });

  const deleteMutation = useMutation({
    mutationFn: (id: number) => apiFetch(`/api/items/${id}`, { method: "DELETE" }),
    onSuccess: () => { qc.invalidateQueries({ queryKey: ["items"] }); setDeleteId(null); toast({ title: "Barang dihapus" }); },
    onError: (e: Error) => toast({ title: "Error", description: e.message, variant: "destructive" }),
  });

  /* ── Handlers ──────────────────────────────────────────────── */
  const openCreate = () => {
    setEditing(null);
    setForm({ code: "", name: "", barcode: "", categoryId: "", unitId: "", supplierId: "", description: "", minimumStock: "0", unitPrice: "" });
    setDialogOpen(true);
  };

  const openEdit = (item: Item) => {
    setEditing(item);
    setForm({
      code: item.code, name: item.name, barcode: item.barcode ?? "",
      categoryId: item.categoryId?.toString() ?? "", unitId: item.unitId?.toString() ?? "",
      supplierId: item.supplierId?.toString() ?? "", description: item.description ?? "",
      minimumStock: item.minimumStock.toString(), unitPrice: item.unitPrice ?? "",
    });
    setDialogOpen(true);
  };

  /* Camera scan detected → backend lookup */
  const handleCameraDetected = useCallback(async (barcode: string) => {
    setScanError("");
    try {
      const result = await apiFetch<Item>(`/api/items/barcode/${encodeURIComponent(barcode)}`);
      if ((result.status ?? "active") !== "active") {
        setScanError("Barang tidak aktif. Material tidak dapat digunakan untuk transaksi.");
        setScanResult(null);
      } else {
        setScanResult(result);
        setCameraScanOpen(false);
        setDetailItem(result);
      }
    } catch {
      setScanError("Barcode tidak ditemukan. Barang belum terdaftar di Master Material.");
    }
  }, []);

  /* Manual scan */
  const handleManualScan = useCallback(async () => {
    const q = manualInput.trim();
    if (!q) return;
    setManualLoading(true);
    setScanError("");
    setScanResult(null);
    try {
      const result = await apiFetch<Item>(`/api/items/barcode/${encodeURIComponent(q)}`);
      setScanResult(result);
      setManualScanOpen(false);
      setDetailItem(result);
    } catch {
      setScanError("Barcode tidak ditemukan.");
    } finally {
      setManualLoading(false);
    }
  }, [manualInput]);

  /* ── Print / Download ──────────────────────────────────────── */
  const handlePrint = (item: Item) => {
    const printWindow = window.open("", "_blank", "width=500,height=400");
    if (!printWindow) return;
    const svg = document.getElementById("barcode-detail-svg");
    const svgHtml = svg?.outerHTML ?? "";
    printWindow.document.write(`
      <html><head><title>Barcode - ${item.name}</title>
      <style>body{display:flex;flex-direction:column;align-items:center;justify-content:center;min-height:100vh;font-family:sans-serif;margin:0;}
      h3{margin:0 0 4px;}p{margin:0;color:#666;font-family:monospace;}</style></head>
      <body><h3>${item.name}</h3><p>${item.code}</p><div style="margin:12px 0">${svgHtml}</div>
      <script>setTimeout(()=>window.print(),300);<\/script></body></html>
    `);
    printWindow.document.close();
  };

  const handleDownload = (item: Item) => {
    const svg = document.getElementById("barcode-detail-svg");
    if (!svg) return;
    const svgData = new XMLSerializer().serializeToString(svg);
    const canvas = document.createElement("canvas");
    const ctx = canvas.getContext("2d");
    const img = new Image();
    img.onload = () => {
      canvas.width = img.width;
      canvas.height = img.height;
      ctx?.drawImage(img, 0, 0);
      const link = document.createElement("a");
      link.download = `barcode-${item.code}.png`;
      link.href = canvas.toDataURL("image/png");
      link.click();
    };
    img.src = "data:image/svg+xml;base64," + btoa(unescape(encodeURIComponent(svgData)));
  };

  const handlePrintLabel = (item: Item) => {
    const printWindow = window.open("", "_blank", "width=400,height=600");
    if (!printWindow) return;
    const svg = document.getElementById("barcode-detail-svg");
    const svgHtml = svg?.outerHTML ?? "";
    printWindow.document.write(`
      <html><head><title>Label - ${item.name}</title>
      <style>body{display:flex;flex-direction:column;align-items:center;justify-content:center;min-height:100vh;font-family:sans-serif;margin:0;padding:24px;}
      .label{border:2px dashed #ccc;border-radius:12px;padding:24px;text-align:center;min-width:240px;}
      .company{font-size:11px;font-weight:bold;letter-spacing:1px;margin:0;}
      h2{margin:8px 0 4px;font-size:16px;}p{margin:2px 0;color:#333;font-size:13px;font-family:monospace;}</style></head>
      <body><div class="label">
        <p class="company">PERUMDAM TIRTA ARDHIA</p>
        <p class="company" style="margin-bottom:8px">RINJANI</p>
        <h2>${item.name}</h2><p>Kode: ${item.code}</p>
        <div style="margin:16px 0">${svgHtml}</div>
        <p>${item.barcode ?? ""}</p>
      </div>
      <script>setTimeout(()=>window.print(),300);<\/script></body></html>
    `);
    printWindow.document.close();
  };

  /* ── Render ────────────────────────────────────────────────── */
  return (
    <div className="p-6 space-y-4">
      {/* Header */}
      <motion.div
        className="flex flex-col sm:flex-row sm:items-center justify-between gap-3"
        initial={{ opacity: 0, y: -20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.4 }}
      >
        <div>
          <h1 className="text-2xl font-bold">Master Barang</h1>
          <p className="text-muted-foreground text-sm">Kelola data barang inventaris</p>
        </div>
        <div className="flex gap-2">
          <Button variant="outline" onClick={() => setCameraScanOpen(true)}>
            <Camera className="w-4 h-4 mr-2" /> Scan Barcode
          </Button>
          <Button onClick={openCreate}><Plus className="w-4 h-4 mr-2" /> Tambah Barang</Button>
        </div>
      </motion.div>

      {/* Table */}
      <motion.div initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.5, delay: 0.1 }}>
        <Card>
          <CardHeader className="pb-3">
            <div className="relative">
              <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" />
              <Input placeholder="Cari nama, kode, barcode..." className="pl-9" value={search} onChange={(e) => setSearch(e.target.value)} />
            </div>
          </CardHeader>
          <CardContent className="p-0">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Kode</TableHead>
                  <TableHead>Nama Barang</TableHead>
                  <TableHead>Kategori</TableHead>
                  <TableHead>Satuan</TableHead>
                  <TableHead>Tracking</TableHead>
                  <TableHead className="text-right">Stok</TableHead>
                  <TableHead className="text-center">Barcode</TableHead>
                  <TableHead>Status</TableHead>
                  <TableHead className="text-right">Aksi</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {isLoading ? (
                  Array(5).fill(0).map((_, i) => (
                    <TableRow key={i}><TableCell colSpan={9}><Skeleton className="h-8 w-full" /></TableCell></TableRow>
                  ))
                ) : !items?.length ? (
                  <TableRow>
                    <TableCell colSpan={9} className="text-center py-12 text-muted-foreground">
                      <Package className="w-8 h-8 mx-auto mb-2 opacity-30" />
                      <p>Belum ada data barang</p>
                    </TableCell>
                  </TableRow>
                ) : (
                  <AnimatePresence mode="popLayout">
                    {items.map((item, idx) => (
                      <motion.tr
                        key={item.id}
                        initial={{ opacity: 0, y: 12 }}
                        animate={{ opacity: 1, y: 0 }}
                        exit={{ opacity: 0, y: -12 }}
                        transition={{ duration: 0.3, delay: idx * 0.03 }}
                        className="border-b transition-colors hover:bg-muted/50"
                      >
                        <TableCell className="font-mono text-sm">{item.code}</TableCell>
                        <TableCell>
                          <p className="font-medium">{item.name}</p>
                        </TableCell>
                        <TableCell>{item.categoryName ?? "-"}</TableCell>
                        <TableCell>{item.unitName ?? "-"}</TableCell>
                        <TableCell>
                          <Badge variant={(item.trackingType ?? "NON_TRACKED") === "TRACKED" ? "default" : "outline"} className="text-[10px]">
                            {(item.trackingType ?? "NON_TRACKED") === "TRACKED" ? "Tracked" : "Non-Tracked"}
                          </Badge>
                        </TableCell>
                        <TableCell className="text-right">
                          <Badge variant={item.currentStock <= item.minimumStock ? "destructive" : "secondary"}>
                            {item.currentStock <= item.minimumStock && <AlertTriangle className="w-3 h-3 mr-1" />}
                            {formatNumber(item.currentStock)}
                          </Badge>
                        </TableCell>
                        <TableCell className="text-center">
                          {item.barcode ? (
                            <motion.div
                              whileHover={{ scale: 1.1 }}
                              transition={{ type: "spring", stiffness: 400, damping: 15 }}
                              className="inline-block cursor-pointer"
                              onClick={() => setDetailItem(item)}
                            >
                              <BarcodeDisplay value={item.barcode} size={36} />
                            </motion.div>
                          ) : (
                            <span className="text-xs text-muted-foreground">-</span>
                          )}
                        </TableCell>
                        <TableCell>
                          <Badge variant={(item.status ?? "active") === "active" ? "default" : "secondary"}>
                            {(item.status ?? "active") === "active" ? "Aktif" : "Nonaktif"}
                          </Badge>
                        </TableCell>
                        <TableCell className="text-right">
                          <div className="flex justify-end gap-1">
                            <motion.div whileHover={{ scale: 1.15 }} whileTap={{ scale: 0.9 }} transition={{ type: "spring", stiffness: 400, damping: 15 }}>
                              <Button size="icon" variant="ghost" className="h-8 w-8" onClick={() => setDetailItem(item)}><Eye className="w-4 h-4" /></Button>
                            </motion.div>
                            <motion.div whileHover={{ scale: 1.15 }} whileTap={{ scale: 0.9 }} transition={{ type: "spring", stiffness: 400, damping: 15 }}>
                              <Button size="icon" variant="ghost" className="h-8 w-8" onClick={() => openEdit(item)}><Pencil className="w-4 h-4" /></Button>
                            </motion.div>
                            <motion.div whileHover={{ scale: 1.15 }} whileTap={{ scale: 0.9 }} transition={{ type: "spring", stiffness: 400, damping: 15 }}>
                              <Button size="icon" variant="ghost" className="h-8 w-8 text-red-500" onClick={() => setDeleteId(item.id)}><Trash2 className="w-4 h-4" /></Button>
                            </motion.div>
                          </div>
                        </TableCell>
                      </motion.tr>
                    ))}
                  </AnimatePresence>
                )}
              </TableBody>
            </Table>
          </CardContent>
        </Card>
      </motion.div>

      {/* ── Camera Scanner ──────────────────────────────────────── */}
      <BarcodeScanner
        open={cameraScanOpen}
        onClose={() => { setCameraScanOpen(false); setScanError(""); }}
        onDetected={handleCameraDetected}
      />

      {/* ── Add / Edit Dialog ───────────────────────────────────── */}
      <Dialog open={dialogOpen} onOpenChange={setDialogOpen}>
        <DialogContent className="max-w-lg max-h-[90vh] overflow-y-auto">
          <DialogHeader><DialogTitle>{editing ? "Edit Barang" : "Tambah Barang"}</DialogTitle></DialogHeader>
          <div className="space-y-3 py-2">
            <div className="grid grid-cols-2 gap-3">
              <div className="space-y-1.5"><Label>Kode *</Label><Input value={form.code} onChange={e => setForm(f => ({ ...f, code: e.target.value }))} placeholder="MAT-PIPA-001" /></div>
              <div className="space-y-1.5"><Label>Nama *</Label><Input value={form.name} onChange={e => setForm(f => ({ ...f, name: e.target.value }))} /></div>
            </div>
            <div className="space-y-1.5"><Label>Barcode</Label><Input value="[AUTO GENERATED]" readOnly className="bg-muted text-muted-foreground" /></div>
            <div className="grid grid-cols-3 gap-3">
              <div className="space-y-1.5"><Label>Kategori</Label>
                <Select value={form.categoryId} onValueChange={v => setForm(f => ({ ...f, categoryId: v }))}>
                  <SelectTrigger><SelectValue placeholder="Pilih" /></SelectTrigger>
                  <SelectContent>{categories?.map(c => <SelectItem key={c.id} value={c.id.toString()}>{c.name}</SelectItem>)}</SelectContent>
                </Select>
              </div>
              <div className="space-y-1.5"><Label>Satuan</Label>
                <Select value={form.unitId} onValueChange={v => setForm(f => ({ ...f, unitId: v }))}>
                  <SelectTrigger><SelectValue placeholder="Pilih" /></SelectTrigger>
                  <SelectContent>{units?.map(u => <SelectItem key={u.id} value={u.id.toString()}>{u.name}</SelectItem>)}</SelectContent>
                </Select>
              </div>
              <div className="space-y-1.5"><Label>Supplier</Label>
                <Select value={form.supplierId} onValueChange={v => setForm(f => ({ ...f, supplierId: v }))}>
                  <SelectTrigger><SelectValue placeholder="Pilih" /></SelectTrigger>
                  <SelectContent>{suppliers?.map(s => <SelectItem key={s.id} value={s.id.toString()}>{s.name}</SelectItem>)}</SelectContent>
                </Select>
              </div>
            </div>
            <div className="grid grid-cols-2 gap-3">
              <div className="space-y-1.5"><Label>Stok Minimum</Label><Input type="number" min="0" value={form.minimumStock} onChange={e => setForm(f => ({ ...f, minimumStock: e.target.value }))} /></div>
              <div className="space-y-1.5"><Label>Harga Satuan</Label><Input type="number" min="0" value={form.unitPrice} onChange={e => setForm(f => ({ ...f, unitPrice: e.target.value }))} /></div>
            </div>
            <div className="space-y-1.5"><Label>Deskripsi</Label><Textarea value={form.description} onChange={e => setForm(f => ({ ...f, description: e.target.value }))} rows={2} /></div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setDialogOpen(false)}>Batal</Button>
            <Button onClick={() => saveMutation.mutate()} disabled={!form.code || !form.name || saveMutation.isPending}>
              {saveMutation.isPending ? "Menyimpan..." : editing ? "Perbarui" : "Simpan"}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* ── Delete Confirmation ─────────────────────────────────── */}
      <Dialog open={deleteId !== null} onOpenChange={(o) => !o && setDeleteId(null)}>
        <DialogContent className="max-w-sm">
          <DialogHeader><DialogTitle>Hapus Barang?</DialogTitle></DialogHeader>
          <p className="text-sm text-muted-foreground py-2">Tindakan ini tidak dapat dibatalkan.</p>
          <DialogFooter>
            <Button variant="outline" onClick={() => setDeleteId(null)}>Batal</Button>
            <Button variant="destructive" onClick={() => deleteId && deleteMutation.mutate(deleteId)} disabled={deleteMutation.isPending}>
              {deleteMutation.isPending ? "Menghapus..." : "Hapus"}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* ── Detail / Barcode Dialog ─────────────────────────────── */}
      <AnimatePresence>
        {detailItem && (
          <Dialog open={!!detailItem} onOpenChange={(o) => !o && setDetailItem(null)}>
            <DialogContent className="max-w-md">
              <motion.div initial={{ opacity: 0, scale: 0.95 }} animate={{ opacity: 1, scale: 1 }} transition={{ type: "spring", damping: 20, stiffness: 250 }}>
                <DialogHeader><DialogTitle>Detail Barang</DialogTitle></DialogHeader>
                <div className="space-y-4 py-3">
                  <div className="grid grid-cols-2 gap-2 text-sm">
                    <div><span className="text-muted-foreground">Kode</span><p className="font-mono font-medium">{detailItem.code}</p></div>
                    <div><span className="text-muted-foreground">Nama</span><p className="font-medium">{detailItem.name}</p></div>
                    <div><span className="text-muted-foreground">Kategori</span><p>{detailItem.categoryName ?? "-"}</p></div>
                    <div><span className="text-muted-foreground">Satuan</span><p>{detailItem.unitName ?? "-"}</p></div>
                    <div><span className="text-muted-foreground">Tracking</span><p>{(detailItem.trackingType ?? "NON_TRACKED") === "TRACKED" ? "Tracked" : "Non-Tracked"}</p></div>
                    <div><span className="text-muted-foreground">Stok</span><p>{formatNumber(detailItem.currentStock)} / min {formatNumber(detailItem.minimumStock)}</p></div>
                    <div><span className="text-muted-foreground">Status</span>
                      <Badge variant={(detailItem.status ?? "active") === "active" ? "default" : "secondary"}>
                        {(detailItem.status ?? "active") === "active" ? "Aktif" : "Nonaktif"}
                      </Badge>
                    </div>
                  </div>

                  {/* Barcode */}
                  {detailItem.barcode && (
                    <motion.div
                      className="flex flex-col items-center py-4 px-6 bg-muted/30 rounded-xl"
                      initial={{ opacity: 0, y: 16 }}
                      animate={{ opacity: 1, y: 0 }}
                      transition={{ delay: 0.15, type: "spring", damping: 18, stiffness: 200 }}
                    >
                      <div id="barcode-detail-svg">
                        <BarcodeDisplay value={detailItem.barcode} size={160} showValue />
                      </div>
                    </motion.div>
                  )}

                  {/* Actions */}
                  {detailItem.barcode && (
                    <div className="flex gap-2">
                      <motion.div className="flex-1" whileHover={{ scale: 1.02 }} whileTap={{ scale: 0.98 }}>
                        <Button variant="outline" className="w-full" onClick={() => handlePrint(detailItem)}>
                          <Printer className="w-4 h-4 mr-2" /> Print
                        </Button>
                      </motion.div>
                      <motion.div className="flex-1" whileHover={{ scale: 1.02 }} whileTap={{ scale: 0.98 }}>
                        <Button variant="outline" className="w-full" onClick={() => handleDownload(detailItem)}>
                          <Download className="w-4 h-4 mr-2" /> Download
                        </Button>
                      </motion.div>
                      <motion.div className="flex-1" whileHover={{ scale: 1.02 }} whileTap={{ scale: 0.98 }}>
                        <Button variant="outline" className="w-full" onClick={() => handlePrintLabel(detailItem)}>
                          <Tag className="w-4 h-4 mr-2" /> Label
                        </Button>
                      </motion.div>
                    </div>
                  )}
                </div>
              </motion.div>
            </DialogContent>
          </Dialog>
        )}
      </AnimatePresence>
    </div>
  );
}
